### ISSUE TITLE
QDataManager and reading IP address

### ISSUE THREAD

**Issue by AI10068** [Mecalc/QuantusSoftware#8]
What would be the solution, if the QDataManager cannot read the IP address?

**Comment by ErnstSwanepoel** [comment]
When QDataManager cant read the IP address then there is most likely a network connection problem.
Check that your network cable is plugged in correctly, ensure your PC is on the same network and your network settings are correct.
Sometimes the PC is set to a static IP address, and this would prohibit your PC from communicating with the MicroQ if it's IP is not set to the same subnet.

As a last resort, you can try to reset the MicroQ to defaults. You can read the manual to see how to do this.
